# Generated by Django 3.0 on 2020-06-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CauHinh', '0004_auto_20200601_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cauhinhseo',
            name='robots',
            field=models.CharField(choices=[('noindex,nofollow', 'Chặn google lập chỉ mục trang web :(noindex,nofollow)'), ('index,follow', 'Lập chỉ mục trang web (index,follow)')], default='index,follow', help_text='Tùy chỉnh lập chỉ mục trang web với google', max_length=100, verbose_name='Robots'),
        ),
    ]
