# Generated by Django 3.0 on 2020-05-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giohang', '0002_giohang_ngaytao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giohang',
            name='ngaytao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
