# Generated by Django 2.2.6 on 2020-05-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoadon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoadon',
            name='DiaChiNguoiNhan',
            field=models.TextField(default='', verbose_name='Địa chỉ người nhận'),
        ),
        migrations.AddField(
            model_name='hoadon',
            name='HoTenNguoiNhan',
            field=models.CharField(default='', max_length=200, verbose_name='Họ tên người nhận'),
        ),
        migrations.AddField(
            model_name='hoadon',
            name='SDT',
            field=models.CharField(default='', max_length=10, verbose_name='Số điện thoại người nhận'),
        ),
    ]
