# Generated by Django 3.0 on 2020-06-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMucTinTuc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=500, null=True, verbose_name='Tên danh mục tin tức')),
                ('duong_dan', models.SlugField(default='', max_length=100, verbose_name='Đường dẫn')),
            ],
            options={
                'verbose_name_plural': 'Danh mục tin tức',
            },
        ),
        migrations.CreateModel(
            name='TinTuc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.TextField(null=True, verbose_name='Tiêu đề')),
                ('mo_ta_ngan', models.TextField(null=True, verbose_name='Mô tả ngắn')),
                ('noi_dung', models.TextField(null=True, verbose_name='Nội dung')),
                ('anh', models.ImageField(default='product-default.jpg', upload_to='', verbose_name='Ảnh')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('duong_dan', models.SlugField(default='', max_length=200, verbose_name='Đường dẫn')),
            ],
            options={
                'verbose_name_plural': 'Tin tức',
            },
        ),
    ]
