# Generated by Django 2.2.6 on 2020-05-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0002_auto_20200529_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='Gia',
            field=models.IntegerField(default=0, verbose_name='Giá bán'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='SoSim',
            field=models.CharField(max_length=100, verbose_name='Số sim'),
        ),
    ]
